#!/usr/bin/env python3
"""Deterministic BestDealHunter branded deal cards (free: Pillow + the bundled OFL font).

Policy (issue #1, agreed with Alpha):
* Every number on a card (price, reference price, % off, savings, verification date)
  is computed from the validated deal record. Nothing is typed by hand or generated by AI.
* Product imagery appears only when the deal names an authorized local photo in
  `image_source` (images/source/...). Without one, the card uses a typographic layout
  with no product picture, so no product is ever fabricated.
* Retailer names are plain text, never logos.

Sizes: 1080x1350 (Instagram 4:5 feed, "feed") and 1080x1080 ("square").

Usage:
  python scripts/deal_graphics.py --preview   # render every deals.json card into docs/graphics-previews/ for review
"""
import argparse
import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "assets" / "fonts" / "Montserrat-Variable.ttf"
SOURCE = ROOT / "images" / "source"
PREVIEWS = ROOT / "docs" / "graphics-previews"
SIZES = {"feed": (1080, 1350), "square": (1080, 1080)}

NAVY, NAVY_2, INK = "#0B1B33", "#16305A", "#0B1B33"
YELLOW, RED, WHITE, MUTED, PAPER = "#FACC15", "#DC2626", "#FFFFFF", "#94A3B8", "#F8FAFC"
REFERENCE_LABELS = {"Best Buy": "Comparable value", "Amazon": "List price", "Macy's": "Original price"}
_fonts = {}


class CardError(ValueError):
    pass


def font(size, weight=700):
    key = (size, weight)
    if key not in _fonts:
        face = ImageFont.truetype(str(FONT), size)
        face.set_variation_by_axes([weight])
        _fonts[key] = face
    return _fonts[key]


def money(value):
    value = float(value)
    return f"${value:,.0f}" if value == int(value) else f"${value:,.2f}"


def card_facts(deal):
    """Everything printed on a card, derived only from the deal record."""
    try:
        price, original = float(deal["price"]), float(deal["original_price"])
        title, store = str(deal["title"]).strip(), str(deal["store"]).strip()
    except (KeyError, TypeError, ValueError) as exc:
        raise CardError(f"deal is missing card data: {exc}") from None
    if not (0 < price < original) or not title or not store:
        raise CardError("deal needs a title, store and 0 < price < original_price")
    verified = deal.get("verified_date")
    try:
        day = date.fromisoformat(verified) if verified else None
        verified_text = f"{day:%b} {day.day}, {day.year}" if day else None
    except ValueError:
        raise CardError("verified_date must be YYYY-MM-DD") from None
    return {
        "title": title,
        "store": store,
        "price": money(price),
        "reference": money(original),
        "reference_label": deal.get("reference_price_label") or REFERENCE_LABELS.get(store, "Reference price"),
        "percent": int((original - price) * 100 // original),  # floor: never overstate the discount
        "savings": money(round(original - price, 2)),
        "verified": verified_text,
        "category": str(deal.get("category") or "").upper(),
    }


def authorized_photo(deal):
    raw = deal.get("image_source")
    if raw is None:
        return None
    if not isinstance(raw, str) or not re.fullmatch(r"images/source/[\w.-]+\.(?:png|jpe?g|webp)", raw, re.I):
        raise CardError("image_source must be an authorized photo under images/source/")
    path = (ROOT / raw).resolve()
    if not path.is_relative_to(SOURCE.resolve()) or not path.is_file():
        raise CardError(f"image_source not found: {raw}")
    return path


# ---------------------------------------------------------------- drawing helpers

def text_width(draw, text, face):
    return draw.textlength(text, font=face)


def wrap(draw, text, face, max_width, max_lines):
    words, lines, current = text.split(), [], ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if text_width(draw, candidate, face) <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    if len(lines) > max_lines:
        lines = lines[:max_lines]
        while lines[-1] and text_width(draw, lines[-1] + "…", face) > max_width:
            lines[-1] = lines[-1][:-1].rstrip()
        lines[-1] += "…"
    return lines


def fit(draw, text, weight, start, max_width, minimum=24):
    size = start
    while size > minimum and text_width(draw, text, font(size, weight)) > max_width:
        size -= 2
    return font(size, weight)


def gradient(size):
    w, h = size
    top, bottom = Image.new("RGB", size, NAVY), Image.new("RGB", size, NAVY_2)
    mask = Image.linear_gradient("L").resize((w, h))
    base = Image.composite(bottom, top, mask)
    glow = Image.new("L", size, 0)
    ImageDraw.Draw(glow).ellipse((w * 0.35, -h * 0.25, w * 1.35, h * 0.55), fill=70)
    return Image.composite(Image.new("RGB", size, "#24477F"), base, glow.filter(ImageFilter.GaussianBlur(120)))


def shadowed_panel(canvas, box, radius, fill):
    x0, y0, x1, y1 = box
    shadow = Image.new("L", canvas.size, 0)
    ImageDraw.Draw(shadow).rounded_rectangle((x0, y0 + 14, x1, y1 + 14), radius, fill=110)
    canvas.paste(Image.new("RGB", canvas.size, "#050B16"), (0, 0), shadow.filter(ImageFilter.GaussianBlur(22)))
    ImageDraw.Draw(canvas).rounded_rectangle(box, radius, fill=fill)


def wordmark(draw, x, y, size):
    parts = (("Best", WHITE), ("Deal", YELLOW), ("Hunter", WHITE))
    face = font(size, 800)
    for word, colour in parts:
        draw.text((x, y), word, font=face, fill=colour)
        x += text_width(draw, word, face)
    return x


def pill(draw, right, y, text, face, fg, bg, pad=(26, 12)):
    w = text_width(draw, text, face)
    box = (right - w - 2 * pad[0], y, right, y + face.size + 2 * pad[1])
    draw.rounded_rectangle(box, radius=(box[3] - box[1]) // 2, fill=bg)
    draw.text((box[0] + pad[0], y + pad[1] - face.size * 0.08), text, font=face, fill=fg)
    return box


def badge(canvas, center, radius, facts):
    draw = ImageDraw.Draw(canvas)
    cx, cy = center
    draw.ellipse((cx - radius, cy - radius, cx + radius, cy + radius), fill=RED, outline=WHITE, width=8)
    pct = f"{facts['percent']}%"
    face = fit(draw, pct, 900, int(radius * 0.74), radius * 1.42)
    draw.text((cx, cy - radius * 0.12), pct, font=face, fill=WHITE, anchor="ms")
    draw.text((cx, cy + radius * 0.32), "OFF", font=font(int(radius * 0.36), 800), fill=WHITE, anchor="ms")


# ---------------------------------------------------------------- layout

def render_card(deal, kind="feed"):
    facts = card_facts(deal)
    photo_path = authorized_photo(deal)
    w, h = SIZES[kind]
    square = kind == "square"
    canvas = gradient((w, h))
    draw = ImageDraw.Draw(canvas)
    margin = 64

    # Header: wordmark + retailer as plain text (no logos).
    wordmark(draw, margin, 58, 50)
    pill(draw, w - margin, 56, facts["store"].upper(), font(28, 800), INK, YELLOW)
    draw.line((margin, 136, w - margin, 136), fill="#2B4A7A", width=2)

    hero_top, hero_bottom = 170, (560 if square else 760)
    if photo_path:
        panel = (margin, hero_top, w - margin, hero_bottom)
        shadowed_panel(canvas, panel, 36, PAPER)
        with Image.open(photo_path) as src:
            photo = ImageOps.exif_transpose(src).convert("RGB")
        photo.thumbnail((panel[2] - panel[0] - 80, panel[3] - panel[1] - 80), Image.Resampling.LANCZOS)
        canvas.paste(photo, ((w - photo.width) // 2, (panel[1] + panel[3] - photo.height) // 2))
        radius = 104 if square else 124
        badge(canvas, (w - margin - radius - 24, hero_top + radius + 24), radius, facts)
    else:
        # Typographic hero: the verified discount is the visual, no product picture.
        pct = f"{facts['percent']}%"
        face = fit(draw, pct, 900, 300 if square else 380, w - 2 * margin)
        baseline = hero_top + face.size * 0.86
        draw.text((w / 2, baseline), pct, font=face, fill=YELLOW, anchor="ms")
        draw.text((w / 2, baseline + (70 if square else 96)), "OFF", font=font(78 if square else 96, 900),
                  fill=WHITE, anchor="ms")
        if facts["category"] and not square:
            draw.text((w / 2, baseline + 160), facts["category"], font=font(26, 700), fill=MUTED, anchor="ms")
    draw = ImageDraw.Draw(canvas)

    # Title.
    y = hero_bottom + (34 if square else 46)
    title_face = font(40 if square else 46, 700)
    for line in wrap(draw, facts["title"], title_face, w - 2 * margin, 2 if square else 3):
        draw.text((margin, y), line, font=title_face, fill=WHITE)
        y += title_face.size * 1.22

    # Price card.
    card_h = 200 if square else 230
    card_top = h - card_h - (112 if square else 128)
    shadowed_panel(canvas, (margin, card_top, w - margin, card_top + card_h), 30, WHITE)
    draw = ImageDraw.Draw(canvas)
    price_face = fit(draw, facts["price"], 900, 112 if square else 128, 520)
    draw.text((margin + 44, card_top + card_h / 2 + price_face.size * 0.36), facts["price"], font=price_face,
              fill=INK, anchor="ls")
    right = w - margin - 44
    ref_face = font(30, 600)
    ref_y = card_top + card_h / 2 - 42
    draw.text((right, ref_y), facts["reference_label"], font=font(24, 600), fill="#64748B", anchor="rs")
    draw.text((right, ref_y + 42), facts["reference"], font=ref_face, fill="#64748B", anchor="rs")
    ref_w = text_width(draw, facts["reference"], ref_face)
    draw.line((right - ref_w, ref_y + 31, right, ref_y + 31), fill=RED, width=4)
    save_face = font(28, 800)
    save_text = f"SAVE {facts['savings']}"
    sw = text_width(draw, save_text, save_face)
    save_box = (right - sw - 44, ref_y + 64, right, ref_y + 116)
    draw.rounded_rectangle(save_box, radius=26, fill=RED)
    draw.text(((save_box[0] + save_box[2]) / 2, save_box[3] - 15), save_text, font=save_face, fill=WHITE, anchor="ms")

    # Footer: verification date + disclosures, always present.
    foot = font(24, 600)
    verified = f"Price verified {facts['verified']}" if facts["verified"] else "Price verification pending"
    draw.text((margin, h - (68 if square else 78)), f"{verified} · Prices and availability may change",
              font=foot, fill=MUTED)
    draw.text((margin, h - (36 if square else 44)), "#ad · We may earn a commission · Link in bio",
              font=foot, fill=MUTED)
    return canvas


def card_id(deal):
    return hashlib.sha256(str(deal.get("url", "")).encode()).hexdigest()[:12]


def save(card, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    card.save(path, "JPEG", quality=92, optimize=True, progressive=True)
    return path


def render_previews(deals, out=PREVIEWS, log=print):
    written = []
    for deal in deals:
        try:
            for kind in SIZES:
                written.append(save(render_card(deal, kind), out / f"{card_id(deal)}-{kind}.jpg"))
        except CardError as exc:
            log(f"Skipped {deal.get('title', 'Untitled')}: {exc}")
    return written


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render BestDealHunter deal cards")
    parser.add_argument("--preview", action="store_true", help="render all deals.json cards to docs/graphics-previews/ for review")
    args = parser.parse_args(argv)
    if not args.preview:
        parser.print_help()
        return 0
    deals = json.loads((ROOT / "deals.json").read_text(encoding="utf-8"))
    for path in render_previews(deals):
        print(f"Rendered {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
